name: Secrets Management Guide

# This workflow demonstrates how to use secrets in GitHub Actions
# To set up secrets, go to: Repository Settings > Secrets and variables > Actions

on:
  workflow_dispatch:  # Manual trigger only
  
env:
  # Example environment variables using secrets
  SITE_NAME: ${{ secrets.SITE_NAME }}
  CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
  GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
  
jobs:
  secrets-demo:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup secrets for deployment
      run: |
        echo "Setting up deployment secrets..."
        echo "Available secrets (values hidden for security):"
        echo "- SITE_NAME: ${{ secrets.SITE_NAME != '' && 'Set ✓' || 'Not set ✗' }}"
        echo "- CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL != '' && 'Set ✓' || 'Not set ✗' }}"
        echo "- GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID != '' && 'Set ✓' || 'Not set ✗' }}"
        
    - name: Configure site with secrets
      if: ${{ secrets.SITE_NAME != '' }}
      run: |
        echo "Configuring site with secrets..."
        # Replace placeholders in HTML files with actual values
        if [ ! -z "${{ secrets.CONTACT_EMAIL }}" ]; then
          find . -name "*.html" -exec sed -i "s/contact@greenbluerestbangkok.com/${{ secrets.CONTACT_EMAIL }}/g" {} \;
        fi
        
        if [ ! -z "${{ secrets.GOOGLE_ANALYTICS_ID }}" ]; then
          echo "Google Analytics ID configured"
        fi
        
        echo "Site configuration completed"
        
    - name: Secrets validation
      run: |
        echo "=== SECRETS SETUP GUIDE ==="
        echo ""
        echo "To set up secrets for this repository:"
        echo "1. Go to: Repository Settings > Secrets and variables > Actions"
        echo "2. Click 'New repository secret' for each of the following:"
        echo ""
        echo "Required secrets:"
        echo "- SITE_NAME: Green Blue Rest Bangkok"
        echo "- CONTACT_EMAIL: your-contact@email.com"
        echo "- GOOGLE_ANALYTICS_ID: your-ga-id (optional)"
        echo ""
        echo "Optional secrets for advanced deployment:"
        echo "- FTP_HOST: your-ftp-host.com"
        echo "- FTP_USERNAME: your-ftp-username"
        echo "- FTP_PASSWORD: your-ftp-password"
        echo "- DOMAIN_NAME: your-custom-domain.com"
        echo ""
        echo "After setting secrets, they will be automatically used in deployments."